version: 2.1

jobs:
  test_failure:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run echo "jejeje"
      - run:
        command: echo "sema kimeumana"
        when: on_fail

workflows:
  badlands:
    jobs:
      - test_failure